import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import chatGPTLogo from '@/assets/chatgptLogo.svg';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ChatGPT Clone",
  description: "Generated by create next app",
  icons: chatGPTLogo,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
